sudo: required
services:
  - docker

before_install:
  - docker build -t jaykishank/react-test -f ./client/Dockerfile.dev ./client/.

script:
  - docker run -e CI=true jaykishank/react-test npm run test -- --coverage

after_success:
  - docker build -t jaykishank/multi-client ./client
  - docker build -t jaykishank/multi-nginx ./nginx
  - docker build -t jaykishank/multi-server ./server
  - docker build -t jaykishank/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jaykishank/multi-client
  - docker push jaykishank/multi-nginx
  - docker push jaykishank/multi-server
  - docker push jaykishank/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-341097230437
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

