version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:80"
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPASSOWRD=postgres_passport
      - PGPORT=5432
      - PGDATABASE=postgres
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379 

